"""In-process federated simulation (no ray, no network).

Week 2 Mon: three simulated clients round-trip dummy tensors.
Week 3 Mon: dummies replaced with three simulated *real* clients — each owns a
torch LoRA model and a private synthetic partition, trains with FedProx, and
the server aggregates via the exact-average + SVD path.

The driver calls ``NumPyClient.fit`` directly and reuses the strategy's
aggregation math, so the exact code that runs over gRPC in W7 is exercised
in-process here.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from flwr.client import NumPyClient

from cluster.adapter_format import (
    DEFAULT_RANK,
    TARGET_MODULES,
    LoRAAdapter,
    random_adapter,
)
from cluster.aggregation import aggregate_naive, aggregate_svd
from cluster.client import DummyClient, LoRAClient, ToyLoRAModel


@dataclass
class RoundResult:
    round_id: int
    adapter: LoRAAdapter
    num_clients: int
    client_losses: dict[str, float] = field(default_factory=dict)

    @property
    def mean_loss(self) -> float | None:
        if not self.client_losses:
            return None
        return sum(self.client_losses.values()) / len(self.client_losses)


def make_dummy_clients(n: int = 3) -> list[DummyClient]:
    """Week 2: n clients that echo (and visibly bump) whatever they receive."""
    return [DummyClient(client_id=f"dummy-{i}", num_examples=10 * (i + 1)) for i in range(n)]


def make_real_clients(
    n: int = 3,
    dim: int = 32,
    rank: int = DEFAULT_RANK,
    mu: float = 0.01,
    local_steps: int = 20,
    samples_per_client: int = 64,
    seed: int = 0,
) -> list[LoRAClient]:
    """Week 3: n clients, each with its own synthetic regression partition.

    Every partition is generated by a different ground-truth perturbation of a
    shared base map, giving mild non-IID data — the setting FedProx targets.

    DEMO NOTE (Week 5, gap fix): torch is imported lazily here (rather than at
    module load) so that ``simulation.py`` — and the DummyClient path through
    it — stays importable in environments without torch.
    """
    import torch

    gen = torch.Generator().manual_seed(seed)
    base_true = torch.randn(dim, dim, generator=gen) / dim**0.5
    clients: list[LoRAClient] = []
    for i in range(n):
        model = ToyLoRAModel(dim=dim, rank=rank, target_modules=TARGET_MODULES, seed=seed)
        x = torch.randn(samples_per_client, dim, generator=gen)
        client_shift = 0.1 * torch.randn(dim, dim, generator=gen) / dim**0.5
        y = x @ (base_true + client_shift).T
        clients.append(
            LoRAClient(
                client_id=f"client-{i}",
                model=model,
                data=(x, y),
                mu=mu,
                local_steps=local_steps,
            )
        )
    return clients


def run_round(
    clients: list[NumPyClient],
    global_adapter: LoRAAdapter,
    round_id: int = 0,
    aggregation: str = "svd",
    fit_config: dict | None = None,
) -> RoundResult:
    """One federated round: broadcast -> local fit -> aggregate."""
    global_arrays = global_adapter.to_ndarrays()
    updates: list[LoRAAdapter] = []
    weights: list[float] = []
    losses: dict[str, float] = {}
    for client in clients:
        arrays, num_examples, metrics = client.fit(
            [a.copy() for a in global_arrays], dict(fit_config or {})
        )
        updates.append(
            LoRAAdapter.from_ndarrays(
                arrays,
                rank=global_adapter.rank,
                alpha=global_adapter.alpha,
                target_modules=global_adapter.target_modules,
            )
        )
        weights.append(float(num_examples))
        if "loss" in metrics:
            losses[str(metrics.get("client_id", len(losses)))] = float(metrics["loss"])
    if aggregation == "svd":
        merged = aggregate_svd(iter(updates), weights, rank=global_adapter.rank)
    elif aggregation == "naive":
        merged = aggregate_naive(iter(updates), weights)
    else:
        raise ValueError(f"unknown aggregation {aggregation!r}")
    return RoundResult(
        round_id=round_id, adapter=merged, num_clients=len(clients), client_losses=losses
    )


def run_federated(
    clients: list[NumPyClient],
    initial_adapter: LoRAAdapter | None = None,
    num_rounds: int = 3,
    aggregation: str = "svd",
    dim: int = 32,
    seed: int = 0,
) -> list[RoundResult]:
    """Multi-round loop; returns per-round results (adapter + metrics)."""
    adapter = initial_adapter or random_adapter(dim, dim, seed=seed)
    results: list[RoundResult] = []
    for r in range(num_rounds):
        result = run_round(clients, adapter, round_id=r, aggregation=aggregation)
        adapter = result.adapter
        results.append(result)
    return results


def make_clustered_clients(
    groups: dict[str, int] | None = None,
    dim: int = 32,
    rank: int = DEFAULT_RANK,
    mu: float = 0.01,
    lr: float = 1e-1,
    local_steps: int = 30,
    samples_per_client: int = 64,
    group_shift: float = 1.5,
    client_shift: float = 0.05,
    seed: int = 0,
) -> tuple[dict[str, LoRAClient], dict[str, str]]:
    """Week 8/10: real FedProx clients organized into project groups.

    ``groups`` maps a project/cluster id to its client count (default: two
    clusters x 3 clients, the G2 scenario). All clients share one base map;
    every group adds its own ground-truth shift (``group_shift``) and every
    client a small private one (``client_shift``), so clients within a group
    pull their adapters in a similar direction and groups pull in different
    ones — the structure dynamic re-clustering is meant to find.

    ``lr`` default is 0.1 (was 0.05 while ``DEFAULT_ALPHA`` was 32): the
    effective update rate scales with (alpha/rank)^2, so halving alpha to match
    Edge's lr_alpha=16 needs a ~4x larger step x count product to keep the
    clusters' update directions separable (8/8 seeds recover a wrong warm-start
    label at lr=0.1, 4/8 at the old lr — measured in the Week 6 review).

    Returns ``(clients, warm_start)``: client_id -> client, and client_id ->
    group id (the warm-start assignment).
    """
    import torch

    groups = groups or {"cluster-web": 3, "cluster-sci": 3}
    gen = torch.Generator().manual_seed(seed)
    base_true = torch.randn(dim, dim, generator=gen) / dim**0.5
    clients: dict[str, LoRAClient] = {}
    warm_start: dict[str, str] = {}
    for group_id, count in groups.items():
        shift_g = group_shift * torch.randn(dim, dim, generator=gen) / dim**0.5
        for i in range(count):
            client_id = f"{group_id}/client-{i}"
            model = ToyLoRAModel(dim=dim, rank=rank, target_modules=TARGET_MODULES, seed=seed)
            x = torch.randn(samples_per_client, dim, generator=gen)
            shift_c = client_shift * torch.randn(dim, dim, generator=gen) / dim**0.5
            y = x @ (base_true + shift_g + shift_c).T
            clients[client_id] = LoRAClient(
                client_id=client_id,
                model=model,
                data=(x, y),
                mu=mu,
                lr=lr,
                local_steps=local_steps,
            )
            warm_start[client_id] = group_id
    return clients, warm_start
